Repository richecr/duck-orm, pull requests merged in 2021-10, with the labels that each got.

#21 Add the on_delete and on_update parameters to the ForeignKey field
  duck_orm/sql/fields.py
  duck_orm/sql/relationship.py
  duck_orm/sql/sql.py
  tests/test_duck_postgres.py
  tests/test_duck_postgres_relationship.py
  tests/test_duck_sqlite_relationship.py
Labels: hacktoberfest, hacktoberfest-accepted

#20 Fixed typo on README.md and index.md
  README.md
  docs/index.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#24 Add contributing in menu and issues templates
  .github/ISSUE_TEMPLATE/discuss-o.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/CONTRIBUTING.md
  mkdocs.yml
Labels: hacktoberfest-accepted

#25 add method find_by_id
  duck_orm/model.py
  tests/test_duck_postgres.py
  tests/test_duck_sqlite.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#28 WIP: Version 1.0.0
  CHANGELOG.md
  CONTRIBUTING.md
  docs/CONTRIBUTING.md
  docs/fields/foreignkey.md
  docs/fields/many_to_many.md
  docs/fields/one_to_many.md
  docs/fields/one_to_one.md
  docs/fields/relations.md
  docs/models/index.md
  duck_orm/__init__.py
  duck_orm/exceptions.py
  duck_orm/model.py
  duck_orm/model_manager.py
  duck_orm/sql/fields.py
  duck_orm/sql/postgres/__init__.py
  duck_orm/sql/relationship.py
  duck_orm/sql/sql.py
  duck_orm/sql/sqlite/__init__.py
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
  tests/test_duck_postgres.py
  tests/test_duck_postgres_relationship.py
  tests/test_duck_sqlite.py
  tests/test_duck_sqlite_relationship.py
Labels: enhancement, help wanted, hacktoberfest-accepted
